/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'coinBalance' : IDL.Int,
  'onboardingComplete' : IDL.Bool,
  'lastDebtResetDate' : Time,
});
export const Redemption = IDL.Record({
  'id' : IDL.Nat,
  'coinsSpent' : IDL.Nat,
  'rewardType' : IDL.Variant({
    'customReward' : IDL.Nat,
    'screenTime' : IDL.Nat,
  }),
  'timestamp' : Time,
});
export const Reward = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'coinCost' : IDL.Nat,
});
export const TaskCompletion = IDL.Record({
  'completedAt' : Time,
  'taskTitle' : IDL.Text,
  'taskId' : IDL.Nat,
  'coinsEarned' : IDL.Nat,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : IDL.Opt(Time),
  'title' : IDL.Text,
  'repeatOption' : IDL.Variant({
    'custom' : IDL.Nat,
    'never' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  }),
  'coinReward' : IDL.Nat,
  'isActive' : IDL.Bool,
  'taskType' : IDL.Variant({
    'custom' : IDL.Text,
    'pushups' : IDL.Null,
    'situps' : IDL.Null,
  }),
  'targetReps' : IDL.Nat,
  'priority' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReward' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'custom' : IDL.Text,
          'pushups' : IDL.Null,
          'situps' : IDL.Null,
        }),
        IDL.Nat,
        IDL.Nat,
        IDL.Variant({
          'custom' : IDL.Nat,
          'never' : IDL.Null,
          'daily' : IDL.Null,
          'weekly' : IDL.Null,
        }),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'deleteReward' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'getRedemptionHistory' : IDL.Func([], [IDL.Vec(Redemption)], ['query']),
  'getRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
  'getTaskCompletionHistory' : IDL.Func(
      [],
      [IDL.Vec(TaskCompletion)],
      ['query'],
    ),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markOnboardingComplete' : IDL.Func([], [], []),
  'redeemCustomReward' : IDL.Func([IDL.Nat], [], []),
  'redeemScreenTime' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateReward' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'updateTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Variant({
          'custom' : IDL.Text,
          'pushups' : IDL.Null,
          'situps' : IDL.Null,
        }),
        IDL.Nat,
        IDL.Nat,
        IDL.Variant({
          'custom' : IDL.Nat,
          'never' : IDL.Null,
          'daily' : IDL.Null,
          'weekly' : IDL.Null,
        }),
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'coinBalance' : IDL.Int,
    'onboardingComplete' : IDL.Bool,
    'lastDebtResetDate' : Time,
  });
  const Redemption = IDL.Record({
    'id' : IDL.Nat,
    'coinsSpent' : IDL.Nat,
    'rewardType' : IDL.Variant({
      'customReward' : IDL.Nat,
      'screenTime' : IDL.Nat,
    }),
    'timestamp' : Time,
  });
  const Reward = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'coinCost' : IDL.Nat,
  });
  const TaskCompletion = IDL.Record({
    'completedAt' : Time,
    'taskTitle' : IDL.Text,
    'taskId' : IDL.Nat,
    'coinsEarned' : IDL.Nat,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : IDL.Opt(Time),
    'title' : IDL.Text,
    'repeatOption' : IDL.Variant({
      'custom' : IDL.Nat,
      'never' : IDL.Null,
      'daily' : IDL.Null,
      'weekly' : IDL.Null,
    }),
    'coinReward' : IDL.Nat,
    'isActive' : IDL.Bool,
    'taskType' : IDL.Variant({
      'custom' : IDL.Text,
      'pushups' : IDL.Null,
      'situps' : IDL.Null,
    }),
    'targetReps' : IDL.Nat,
    'priority' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReward' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'addTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'custom' : IDL.Text,
            'pushups' : IDL.Null,
            'situps' : IDL.Null,
          }),
          IDL.Nat,
          IDL.Nat,
          IDL.Variant({
            'custom' : IDL.Nat,
            'never' : IDL.Null,
            'daily' : IDL.Null,
            'weekly' : IDL.Null,
          }),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'deleteReward' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'getRedemptionHistory' : IDL.Func([], [IDL.Vec(Redemption)], ['query']),
    'getRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
    'getTaskCompletionHistory' : IDL.Func(
        [],
        [IDL.Vec(TaskCompletion)],
        ['query'],
      ),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markOnboardingComplete' : IDL.Func([], [], []),
    'redeemCustomReward' : IDL.Func([IDL.Nat], [], []),
    'redeemScreenTime' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateReward' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'updateTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Variant({
            'custom' : IDL.Text,
            'pushups' : IDL.Null,
            'situps' : IDL.Null,
          }),
          IDL.Nat,
          IDL.Nat,
          IDL.Variant({
            'custom' : IDL.Nat,
            'never' : IDL.Null,
            'daily' : IDL.Null,
            'weekly' : IDL.Null,
          }),
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };