/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Redemption {
  'id' : bigint,
  'coinsSpent' : bigint,
  'rewardType' : { 'customReward' : bigint } |
    { 'screenTime' : bigint },
  'timestamp' : Time,
}
export interface Reward { 'id' : bigint, 'name' : string, 'coinCost' : bigint }
export interface Task {
  'id' : bigint,
  'completedAt' : [] | [Time],
  'title' : string,
  'repeatOption' : { 'custom' : bigint } |
    { 'never' : null } |
    { 'daily' : null } |
    { 'weekly' : null },
  'coinReward' : bigint,
  'isActive' : boolean,
  'taskType' : { 'custom' : string } |
    { 'pushups' : null } |
    { 'situps' : null },
  'targetReps' : bigint,
  'priority' : boolean,
}
export interface TaskCompletion {
  'completedAt' : Time,
  'taskTitle' : string,
  'taskId' : bigint,
  'coinsEarned' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'coinBalance' : bigint,
  'onboardingComplete' : boolean,
  'lastDebtResetDate' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReward' : ActorMethod<[string, bigint], bigint>,
  'addTask' : ActorMethod<
    [
      string,
      { 'custom' : string } |
        { 'pushups' : null } |
        { 'situps' : null },
      bigint,
      bigint,
      { 'custom' : bigint } |
        { 'never' : null } |
        { 'daily' : null } |
        { 'weekly' : null },
      boolean,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'deleteReward' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getRedemptionHistory' : ActorMethod<[], Array<Redemption>>,
  'getRewards' : ActorMethod<[], Array<Reward>>,
  'getTaskCompletionHistory' : ActorMethod<[], Array<TaskCompletion>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markOnboardingComplete' : ActorMethod<[], undefined>,
  'redeemCustomReward' : ActorMethod<[bigint], undefined>,
  'redeemScreenTime' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateReward' : ActorMethod<[bigint, string, bigint], undefined>,
  'updateTask' : ActorMethod<
    [
      bigint,
      string,
      { 'custom' : string } |
        { 'pushups' : null } |
        { 'situps' : null },
      bigint,
      bigint,
      { 'custom' : bigint } |
        { 'never' : null } |
        { 'daily' : null } |
        { 'weekly' : null },
      boolean,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];