/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface TaskCompletion {
    completedAt: Time;
    taskTitle: string;
    taskId: bigint;
    coinsEarned: bigint;
}
export interface Reward {
    id: bigint;
    name: string;
    coinCost: bigint;
}
export interface Redemption {
    id: bigint;
    coinsSpent: bigint;
    rewardType: {
        __kind__: "customReward";
        customReward: bigint;
    } | {
        __kind__: "screenTime";
        screenTime: bigint;
    };
    timestamp: Time;
}
export interface Task {
    id: bigint;
    completedAt?: Time;
    title: string;
    repeatOption: {
        __kind__: "custom";
        custom: bigint;
    } | {
        __kind__: "never";
        never: null;
    } | {
        __kind__: "daily";
        daily: null;
    } | {
        __kind__: "weekly";
        weekly: null;
    };
    coinReward: bigint;
    isActive: boolean;
    taskType: {
        __kind__: "custom";
        custom: string;
    } | {
        __kind__: "pushups";
        pushups: null;
    } | {
        __kind__: "situps";
        situps: null;
    };
    targetReps: bigint;
    priority: boolean;
}
export interface UserProfile {
    coinBalance: bigint;
    onboardingComplete: boolean;
    lastDebtResetDate: Time;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addReward(name: string, coinCost: bigint): Promise<bigint>;
    addTask(title: string, taskType: {
        __kind__: "custom";
        custom: string;
    } | {
        __kind__: "pushups";
        pushups: null;
    } | {
        __kind__: "situps";
        situps: null;
    }, targetReps: bigint, coinReward: bigint, repeatOption: {
        __kind__: "custom";
        custom: bigint;
    } | {
        __kind__: "never";
        never: null;
    } | {
        __kind__: "daily";
        daily: null;
    } | {
        __kind__: "weekly";
        weekly: null;
    }, priority: boolean): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeTask(taskId: bigint): Promise<void>;
    deleteReward(rewardId: bigint): Promise<void>;
    deleteTask(taskId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProfile(): Promise<UserProfile>;
    getRedemptionHistory(): Promise<Array<Redemption>>;
    getRewards(): Promise<Array<Reward>>;
    getTaskCompletionHistory(): Promise<Array<TaskCompletion>>;
    getTasks(): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markOnboardingComplete(): Promise<void>;
    redeemCustomReward(rewardId: bigint): Promise<void>;
    redeemScreenTime(minutes: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateReward(rewardId: bigint, name: string, coinCost: bigint): Promise<void>;
    updateTask(taskId: bigint, title: string, taskType: {
        __kind__: "custom";
        custom: string;
    } | {
        __kind__: "pushups";
        pushups: null;
    } | {
        __kind__: "situps";
        situps: null;
    }, targetReps: bigint, coinReward: bigint, repeatOption: {
        __kind__: "custom";
        custom: bigint;
    } | {
        __kind__: "never";
        never: null;
    } | {
        __kind__: "daily";
        daily: null;
    } | {
        __kind__: "weekly";
        weekly: null;
    }, priority: boolean, isActive: boolean): Promise<void>;
}
import type { Redemption as _Redemption, Task as _Task, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addReward(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addReward(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReward(arg0, arg1);
            return result;
        }
    }
    async addTask(arg0: string, arg1: {
        __kind__: "custom";
        custom: string;
    } | {
        __kind__: "pushups";
        pushups: null;
    } | {
        __kind__: "situps";
        situps: null;
    }, arg2: bigint, arg3: bigint, arg4: {
        __kind__: "custom";
        custom: bigint;
    } | {
        __kind__: "never";
        never: null;
    } | {
        __kind__: "daily";
        daily: null;
    } | {
        __kind__: "weekly";
        weekly: null;
    }, arg5: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_variant_n2(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_variant_n2(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0);
            return result;
        }
    }
    async deleteReward(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReward(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return result;
        }
    }
    async getRedemptionHistory(): Promise<Array<Redemption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRedemptionHistory();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRedemptionHistory();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRewards(): Promise<Array<Reward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewards();
            return result;
        }
    }
    async getTaskCompletionHistory(): Promise<Array<TaskCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskCompletionHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskCompletionHistory();
            return result;
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markOnboardingComplete(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markOnboardingComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markOnboardingComplete();
            return result;
        }
    }
    async redeemCustomReward(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemCustomReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemCustomReward(arg0);
            return result;
        }
    }
    async redeemScreenTime(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemScreenTime(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemScreenTime(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateReward(arg0: bigint, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReward(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReward(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: {
        __kind__: "custom";
        custom: string;
    } | {
        __kind__: "pushups";
        pushups: null;
    } | {
        __kind__: "situps";
        situps: null;
    }, arg3: bigint, arg4: bigint, arg5: {
        __kind__: "custom";
        custom: bigint;
    } | {
        __kind__: "never";
        never: null;
    } | {
        __kind__: "daily";
        daily: null;
    } | {
        __kind__: "weekly";
        weekly: null;
    }, arg6: boolean, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_variant_n2(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, to_candid_variant_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_variant_n2(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
}
function from_candid_Redemption_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Redemption): Redemption {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    coinsSpent: bigint;
    rewardType: {
        customReward: bigint;
    } | {
        screenTime: bigint;
    };
    timestamp: _Time;
}): {
    id: bigint;
    coinsSpent: bigint;
    rewardType: {
        __kind__: "customReward";
        customReward: bigint;
    } | {
        __kind__: "screenTime";
        screenTime: bigint;
    };
    timestamp: Time;
} {
    return {
        id: value.id,
        coinsSpent: value.coinsSpent,
        rewardType: from_candid_variant_n11(_uploadFile, _downloadFile, value.rewardType),
        timestamp: value.timestamp
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    completedAt: [] | [_Time];
    title: string;
    repeatOption: {
        custom: bigint;
    } | {
        never: null;
    } | {
        daily: null;
    } | {
        weekly: null;
    };
    coinReward: bigint;
    isActive: boolean;
    taskType: {
        custom: string;
    } | {
        pushups: null;
    } | {
        situps: null;
    };
    targetReps: bigint;
    priority: boolean;
}): {
    id: bigint;
    completedAt?: Time;
    title: string;
    repeatOption: {
        __kind__: "custom";
        custom: bigint;
    } | {
        __kind__: "never";
        never: null;
    } | {
        __kind__: "daily";
        daily: null;
    } | {
        __kind__: "weekly";
        weekly: null;
    };
    coinReward: bigint;
    isActive: boolean;
    taskType: {
        __kind__: "custom";
        custom: string;
    } | {
        __kind__: "pushups";
        pushups: null;
    } | {
        __kind__: "situps";
        situps: null;
    };
    targetReps: bigint;
    priority: boolean;
} {
    return {
        id: value.id,
        completedAt: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.completedAt)),
        title: value.title,
        repeatOption: from_candid_variant_n16(_uploadFile, _downloadFile, value.repeatOption),
        coinReward: value.coinReward,
        isActive: value.isActive,
        taskType: from_candid_variant_n17(_uploadFile, _downloadFile, value.taskType),
        targetReps: value.targetReps,
        priority: value.priority
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customReward: bigint;
} | {
    screenTime: bigint;
}): {
    __kind__: "customReward";
    customReward: bigint;
} | {
    __kind__: "screenTime";
    screenTime: bigint;
} {
    return "customReward" in value ? {
        __kind__: "customReward",
        customReward: value.customReward
    } : "screenTime" in value ? {
        __kind__: "screenTime",
        screenTime: value.screenTime
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: bigint;
} | {
    never: null;
} | {
    daily: null;
} | {
    weekly: null;
}): {
    __kind__: "custom";
    custom: bigint;
} | {
    __kind__: "never";
    never: null;
} | {
    __kind__: "daily";
    daily: null;
} | {
    __kind__: "weekly";
    weekly: null;
} {
    return "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "never" in value ? {
        __kind__: "never",
        never: value.never
    } : "daily" in value ? {
        __kind__: "daily",
        daily: value.daily
    } : "weekly" in value ? {
        __kind__: "weekly",
        weekly: value.weekly
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: string;
} | {
    pushups: null;
} | {
    situps: null;
}): {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "pushups";
    pushups: null;
} | {
    __kind__: "situps";
    situps: null;
} {
    return "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "pushups" in value ? {
        __kind__: "pushups",
        pushups: value.pushups
    } : "situps" in value ? {
        __kind__: "situps",
        situps: value.situps
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Redemption>): Array<Redemption> {
    return value.map((x)=>from_candid_Redemption_n9(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "custom";
    custom: string;
} | {
    __kind__: "pushups";
    pushups: null;
} | {
    __kind__: "situps";
    situps: null;
}): {
    custom: string;
} | {
    pushups: null;
} | {
    situps: null;
} {
    return value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "pushups" ? {
        pushups: value.pushups
    } : value.__kind__ === "situps" ? {
        situps: value.situps
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "custom";
    custom: bigint;
} | {
    __kind__: "never";
    never: null;
} | {
    __kind__: "daily";
    daily: null;
} | {
    __kind__: "weekly";
    weekly: null;
}): {
    custom: bigint;
} | {
    never: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "never" ? {
        never: value.never
    } : value.__kind__ === "daily" ? {
        daily: value.daily
    } : value.__kind__ === "weekly" ? {
        weekly: value.weekly
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
